# Generated by Django 5.2.1 on 2025-05-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Rasm nomi'),
        ),
    ]
