# Generated by Django 5.2.1 on 2025-05-11 12:26

import django.db.models.deletion
import mptt.fields
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, help_text="Agar maxsus shablon ishlatmoqchi bo'lsangiz, uning nomini kiriting (masalan, 'pages/contact_page.html'). Bo'sh qoldirilsa, standart shablon ishlatiladi.", max_length=100, null=True, verbose_name='Template Name')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.CharField(blank=True, help_text="Agar menyu bandi tashqi manzilga yoki maxsus URLga yo'naltirsa (masalan, /yangiliklar/), shu yerga kiriting. 'Link to Page' tanlangan bo'lsa, bu bo'sh qoldiriladi.", max_length=255, verbose_name='Or Custom URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('location', models.CharField(choices=[('main_menu', 'Main Menu (Header)'), ('footer_menu', 'Footer Menu')], default='main_menu', help_text="Bu menyu bandi qaysi menyuda ko'rinishi kerak.", max_length=50, verbose_name='Menu Location')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.menuitem', verbose_name='Parent Item')),
                ('link_page', models.ForeignKey(blank=True, help_text="Agar menyu bandi saytdagi sahifaga yo'naltirsa, shu yerdan tanlang.", null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.page', verbose_name='Link to Page')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuItemTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=100, verbose_name='Menu Item Title')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Item Translation',
                'db_table': 'pages_menuitem_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255, verbose_name='Page Title')),
                ('slug', models.SlugField(help_text="Sahifaning URL manzili, masalan 'biz-haqimizda'. Agar bo'sh qoldirilsa, sarlavhadan avtomatik generatsiya qilinadi.", max_length=270, unique=True, verbose_name='Slug (URL)')),
                ('content', models.TextField(verbose_name='Page Content', null=True, blank=True)),
                ('meta_keywords', models.CharField(blank=True, help_text="SEO uchun kalit so'zlar, vergul bilan ajratilgan.", max_length=255, null=True, verbose_name='Meta Keywords')),
                ('meta_description', models.TextField(blank=True, help_text='SEO uchun sahifa tavsifi.', null=True, verbose_name='Meta Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pages.page')),
            ],
            options={
                'verbose_name': 'Page Translation',
                'db_table': 'pages_page_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
