# Generated by Django 5.2.1 on 2025-05-11 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text="Agar menyu bandi saytdagi sahifaga yo'naltirsa, shu yerdan tanlang.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.page', verbose_name='Link to Page'),
        ),
    ]
