# Generated by Django 5.2.1 on 2025-05-11 12:26

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Publication Category',
                'verbose_name_plural': 'Publication Categories',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications_covers/%Y/%m/', verbose_name='Cover Image')),
                ('file', models.FileField(upload_to='publications_files/%Y/%m/', verbose_name='File')),
                ('publication_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Publication Year')),
                ('publisher', models.CharField(blank=True, max_length=200, null=True, verbose_name='Publisher')),
                ('is_published', models.BooleanField(default=True, verbose_name='Is Published')),
                ('downloads_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Downloads Count')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publications.publicationcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_year', 'translations__title'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PublicationCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Category Name')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='Slug')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='publications.publicationcategory')),
            ],
            options={
                'verbose_name': 'Publication Category Translation',
                'db_table': 'publications_publicationcategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PublicationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(blank=True, null=True, verbose_name='Short Description/Abstract')),
                ('authors', models.CharField(help_text="Vergul bilan ajratilgan mualliflar ro'yxati", max_length=500, verbose_name='Authors')),
                ('content', models.TextField(verbose_name='Content', null=True, blank=True, default='')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='publications.publication')),
            ],
            options={
                'verbose_name': 'Publication Translation',
                'db_table': 'publications_publication_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
