# Generated by Django 5.2.1 on 2025-05-11 19:35

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationtranslation',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='publicationtranslation',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Short Description/Abstract'),
        ),
        migrations.AlterField(
            model_name='publicationtranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
