"""
Django settings for cardio_project project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-exs*34nh*6cmdc%5)itov955&%y&+!k5(h)uypc3tp==vfgllt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'core.apps.CoreConfig',
    'news.apps.NewsConfig',
    'doctors.apps.DoctorsConfig',
    'publications.apps.PublicationsConfig',
    'pages.apps.PagesConfig',
    'parler',
    'django_ckeditor_5',
    'mptt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cardio_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.i18n',
                'core.context_processors.main_menu_items', # Qo'shilgan kontekst protsessor
                'core.context_processors.footer_menu_items',# Qo'shilgan kontekst protsessor
            ],
        },
    },
]


WSGI_APPLICATION = 'cardio_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'uz-UZ'

TIME_ZONE = 'Asia/Tashkent'

from django.utils.translation import gettext_lazy as _

# Saytda mavjud bo'ladigan tillar
LANGUAGES = [
    ('uz', _('Uzbek')),
    ('ru', _('Russian')),
    ('en', _('English')),
]

# Standart til
LANGUAGE_CODE = 'uz' # Yoki 'ru', 'en'

# Lokalizatsiya fayllari qayerda joylashishi
LOCALE_PATHS = [
    BASE_DIR / 'locale', # Loyiha ildizida 'locale' papkasi
]

USE_I18N = True # Xalqaro tillarni yoqish
USE_L10N = True # Lokalizatsiyani yoqish (sana, raqam formatlari)
USE_TZ = True   # Vaqt mintaqalarini hisobga olish


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static', # Loyiha ildizida 'static' papkasi
]
# STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django Parler sozlamalari
PARLER_LANGUAGES = {
    1: ( # SITE_ID ga mos kelishi kerak (odatda 1)
        {'code': 'uz'}, # O'zbekcha
        {'code': 'ru'}, # Ruscha
        {'code': 'en'}, # Inglizcha
    ),
    'default': {
        'fallback': 'uz',             # Agar biror tilda tarjima topilmasa, qaysi tilga qaytish
        'hide_untranslated': False,   # Tarjima qilinmagan obyektlarni yashirish yoki ko'rsatish
    }
}

# CKEditor 5 uchun sozlamalar
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'underline', 'strikethrough', 'code', 'subscript', 'superscript',
            'link', 'bulletedList', 'numberedList', 'todoList', 'blockQuote', 'codeBlock',
            'imageUpload', 'insertTable', 'mediaEmbed', 'horizontalLine', 'pageBreak',
            'undo', 'redo', 'alignment', 'outdent', 'indent', 'fontColor', 'fontBackgroundColor',
            'fontFamily', 'fontSize', 'highlight', 'removeFormat', 'specialCharacters', 'sourceEditing',
            'findAndReplace', 'selectAll', 'htmlEmbed', 'exportPdf', 'exportWord', 'fullScreen',
        ],
    }
}