# Generated by Django 5.2.1 on 2025-05-11 12:26

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='doctors_photos/%Y/%m/', verbose_name='Photo')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of Experience')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active Staff')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ro'yxatda chiqish tartibi", verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctors',
                'ordering': ['order', 'translations__full_name'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='DoctorTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('position', models.CharField(max_length=200, verbose_name='Position/Specialty')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography/Additional Information')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'Doctor Translation',
                'db_table': 'doctors_doctor_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
