# Generated by Django 5.2.1 on 2025-05-11 19:35

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortranslation',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Biography/Additional Information'),
        ),
    ]
